### PR TITLE
mkinitcpio-install.sh: Concatenate units manually.

### LINKED ISSUE #32: mkinitcpio-hook is broken after move to "community"
Hi!
Thanks for this cool project! It worked really great until last update.
<details>

`mkinitcpio -p linux` completes with the following error:
```
==> ERROR: Missing any units in /etc/systemd/system with entry ConditionPathExists=/etc/initrd-release
```

After reboot sshd is not reachable from initrd and I have to wait to the timeout to be able to access the rescure shell.
From there I can unencrypt my root partition and via `systemctl default` continue the boot process as usual.

Something else I noticed besides the missing ability to access via ssh is that I am also unable to use ctrl+alt+Fx keys to get an other tty how I did before to be able to unlock the root partition during the timeout.

Do I need to change my config?
I could not see any *.pacnew config that would have pointed me to update my configs and also I could not see anything obvious in the last couple commits.
</details>

Regards!

### PR DESCRIPTION
**Pull request by dvzrv**
When running in chroot systemctl cat will not work (as no dbus integration exists).
We therefore concatenate the units (top-most only) and any drop-in files that might exist in the various overlays.

Fixes #32

### CODE REVIEW

File: mkinitcpio-install.sh [hunk 1]
```diff
@@ -52,6 +52,33 @@ run_command() {
     esac
 }
 
+concatenate_unit() {
+    # concatenate units and their potential drop-in files
+    # we do this manually, as in a chroot `systemctl cat` will not work
+    local unit_name="$1"
+    local unit_content=""
+    # add the top-most service
```
Comment (Andrei-Pozolotin) [inline mkinitcpio-install.sh]: local service_path=

**Comment by Andrei-Pozolotin** [comment]
also lets not mark issue 32 resolved, keep it open for now

**Comment by Andrei-Pozolotin** [comment]
and then LGTM: feel free to squash/commit/release

File: mkinitcpio-install.sh (hunk 1 above)
Comment (ShapeShifter499) [reply mkinitcpio-install.sh]: What are these changes for?  Just a rename of the variables?

Comment (Andrei-Pozolotin) [reply mkinitcpio-install.sh]: declare these function-local to prevent namespace leak, 
since we work inside larger context of `mkinitcpio` build invocation

Comment (ShapeShifter499) [reply mkinitcpio-install.sh]: Ah

File: mkinitcpio-install.sh [hunk 2]
```diff
@@ -52,6 +52,35 @@ run_command() {
...
 
+concatenate_unit() {
+    # concatenate units and their potential drop-in files
+    # we do this manually, as in a chroot `systemctl cat` will not work
+    local unit_name="$1"
+    local unit_content=""
+    local service_path=""
+    local override=""
+    # add the top-most service
+    for service_path in {/usr/lib,/etc,/run}/systemd/system; do
```
Comment (ml-) [inline mkinitcpio-install.sh]: I don't think runtime changes should be considered since they are always overriden by /etc drop-ins.

Comment (ml-) [reply mkinitcpio-install.sh]: Only the first service file should be taken into account since it's a replacement and not an override (like drop-ins).
Since runtime should not be taken into account, the order is `/etc`, `/usr/lib`.

File: mkinitcpio-install.sh [hunk 3]
```diff
@@ -52,6 +52,35 @@ run_command() {
...
+        if [ -f "${service_path}/${unit_name}" ]; then
+          unit_content=""
+          unit_content+="# ${service_path}/${unit_name}\n"
+          unit_content+="$(cat "${service_path}/${unit_name}")\n\n"
```
Comment (ml-) [inline mkinitcpio-install.sh]: Just echo/printf directly and `break`

```bash
echo "# ${service_path}/${unit_name}"
cat "${service_path}/${unit_name}"
break
```
`echo` will have a linebreak as well es `cat` since it's not stripped due to subshell. You can add additional newlines in the drop-in loop.

**Comment by ml-** [comment]
damn, was only a few minutes away from submitting my review comments

**Comment by Andrei-Pozolotin** [comment]
never too late :-) what was it?

**Comment by dvzrv** [comment]
Ha, we can still add more changes in upcoming pull requests :)

File: mkinitcpio-install.sh [hunk 4]
```diff
@@ -52,6 +52,35 @@ run_command() {
...
+        fi
+    done
+    # add any existing drop-in file for the unit
+    for service_path in {/usr/lib,/etc,/run}/systemd/system; do
```
Comment (ml-) [inline mkinitcpio-install.sh]: same here, no runtime changes but include all dropins starting with `/usr`

File: mkinitcpio-install.sh [hunk 5]
```diff
@@ -52,6 +52,35 @@ run_command() {
...
+        if [ -d "${service_path}/${unit_name}.d" ]; then
+            for override in "${service_path}/${unit_name}.d/"*.conf; do
+                if [ -f "$override" ]; then
+                    unit_content+="# ${override}\n"
+                    unit_content+="$(cat "${override}")\n\n"
```
Comment (ml-) [inline mkinitcpio-install.sh]: Also just print to stdout
```bash
echo
echo "# ${override}"
cat "$override"
```

File: mkinitcpio-install.sh [hunk 6]
```diff
@@ -52,6 +52,35 @@ run_command() {
...
+                fi
+            done
+        fi
+    done
+    echo -e "$unit_content"
```
Comment (ml-) [inline mkinitcpio-install.sh]: this echo won't be required anymore

**Comment by ml-** [comment]
@dvzrv @Andrei-Pozolotin Sure, we can do that in the next PR. Can discuss here though.

**Comment by ml-** [comment]
Also saw this in the systemd changelog, not sure about it yet:
```
        * Unit files now support top level dropin directories of the form
          <unit_type>.d/ (e.g. service.d/) that may be used to add configuration
          that affects all corresponding unit files.
```

**Comment by Andrei-Pozolotin** [comment]
@dvzrv looks like Matthias is right with the above review

File: mkinitcpio-install.sh (hunk 2 above)
Comment (dvzrv) [reply mkinitcpio-install.sh]: Fair enough for the runtime changes.

As the ordering is `/etc`, `/usr/lib` the shell expansion is `for service_path in {/usr/lib,/etc}/systemd/system; do` though (the last one wins in the above implementation).

File: mkinitcpio-install.sh (hunk 3 above)
Comment (dvzrv) [reply mkinitcpio-install.sh]: True I didn't consider that. I have been doing too much python lately :D

File: mkinitcpio-install.sh (hunk 6 above)
Comment (dvzrv) [reply mkinitcpio-install.sh]: Yes, but instead we will have added a few more ;-)

File: mkinitcpio-install.sh (hunk 2 above)
Comment (ml-) [reply mkinitcpio-install.sh]: Yea, I wrote it when I already had my next comment in mind (print and break asap).

**Comment by dvzrv** [comment]
> Also saw this in the systemd changelog, not sure about it yet:

What would be the exact location for those dropin's though? `/etc/systemd/system/service.d/`?
That should be fairly easy to add I guess.

File: mkinitcpio-install.sh (hunk 6 above)
Comment (ml-) [reply mkinitcpio-install.sh]: true. but this is bash ;)

**Comment by Andrei-Pozolotin** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.unit.html
```
Along with a unit file foo.service, a "drop-in" directory foo.service.d/ may exist. All files with the suffix ".conf" from this directory will be parsed after the unit file itself is parsed. This is useful to alter or add configuration settings for a unit, without having to modify unit files. Drop-in files must contain appropriate section headers. For instantiated units, this logic will first look for the instance ".d/" subdirectory (e.g. "foo@bar.service.d/") and read its ".conf" files, followed by the template ".d/" subdirectory (e.g. "foo@.service.d/") and the ".conf" files there. Moreover for units names containing dashes ("-"), the set of directories generated by truncating the unit name after all dashes is searched too. Specifically, for a unit name foo-bar-baz.service not only the regular drop-in directory foo-bar-baz.service.d/ is searched but also both foo-bar-.service.d/ and foo-.service.d/. This is useful for defining common drop-ins for a set of related units, whose names begin with a common prefix. This scheme is particularly useful for mount, automount and slice units, whose systematic naming structure is built around dashes as component separators. Note that equally named drop-in files further down the prefix hierarchy override those further up, i.e. foo-bar-.service.d/10-override.conf overrides foo-.service.d/10-override.conf.

In cases of unit aliases (described above), dropins for the aliased name and all aliases are loaded. In the example of default.target aliasing graphical.target, default.target.d/, default.target.wants/, default.target.requires/, graphical.target.d/, graphical.target.wants/, graphical.target.requires/ would all be read. For templates, dropins for the template, any template aliases, the template instance, and all alias instances are read. When just a specific template instance is aliased, then the dropins for the target template, the target template instance, and the alias template instance are read.

In addition to /etc/systemd/system, the drop-in ".d/" directories for system services can be placed in /usr/lib/systemd/system or /run/systemd/system directories. Drop-in files in /etc take precedence over those in /run which in turn take precedence over those in /usr/lib. Drop-in files under any of these directories take precedence over unit files wherever located. Multiple drop-in files with different names are applied in lexicographic order, regardless of which of the directories they reside in.

Units also support a top-level drop-in with type.d/, where type may be e.g. "service" or "socket", that allows altering or adding to the settings of all corresponding unit files on the system. The formatting and precedence of applying drop-in configurations follow what is defined above. Configurations in type.d/ have the lowest precedence compared to settings in the name specific override directories. So the contents of foo-.service.d/10-override.conf would override service.d/10-override.conf.

Note that while systemd offers a flexible dependency system between units it is recommended to use this functionality only sparingly and instead rely on techniques such as bus-based or socket-based activation which make dependencies implicit, resulting in a both simpler and more flexible system.
```

**Comment by ml-** [comment]
> > Also saw this in the systemd changelog, not sure about it yet:
> 
> What would be the exact location for those dropin's though? `/etc/systemd/system/service.d/`?
> That should be fairly easy to add I guess.

`/etc/systemd/system/service.d` and `/etc/systemd/system/service.d`

**Comment by Andrei-Pozolotin** [comment]
> About runtime: Consider or not?

you guys already convinced me that "users should be protected from the advanced cruft", no? :-)

**Comment by ml-** [comment]
> > About runtime: Consider or not?
> 
> you guys already convinced me that "users should be protected from the advanced cruft", no? :-)

Ok, no runtime changes then.

**Comment by Andrei-Pozolotin** [comment]
@ml- @dvzrv 
Guys please confirm if you want to finish this review
with a new merge/release. Or not? :-)

@dvzrv David: github wants you to fill out both `tag` and `title` 
https://github.com/random-archer/mkinitcpio-systemd-tool/releases
when using `Draft a new release`, i.e. same version value: `v35` for both

**Comment by ml-** [comment]
@Andrei-Pozolotin Sorry for late response. I will have a look at it and maybe some other things as soon as I have some time.

Need to think about a good setup to quickly test the tool in different environments so I don't break it again.

**Comment by Andrei-Pozolotin** [comment]
@ml- great, thank you.
